#!/bin/bash -l
#SBATCH --job-name=cpi_openacc
#SBATCH --account=uzg2
#SBATCH --mail-user=dennys.huber@uzh.ch
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --partition=debug
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread
#SBATCH --output=output.log
#SBATCH --error=error.log
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./cpi_openacc
