#!/bin/bash

start=`date +%s.%N`

factoring=$(factor $1 | wc -w)

if [[ $factoring -gt 2 ]]; then
	echo "$1 is composite!"
elif [[ $factoring -lt 2 ]]; then
	echo "$1 is not composite nor prime"
else
	echo "$1 is prime!"
fi
end=`date +%s.%N`

runtime=$( echo "$end - $start" | bc -l )

echo "Runtime: $runtime seconds"
