#!/bin/bash

start=`date +%s.%N`
if [[ ! $# -eq 1 ]]; then
	echo "error: Not correct number of arguments" >&2
	exit 1
fi

re='^[0-9]+$'
if ! [[ $1 =~ $re ]] ; then
   echo "error: Not an integer" >&2; exit 1
fi

factoring=$(factor $1 | wc -w)

if [[ $factoring -gt 2 ]]; then
	echo "$1 is composite!"
elif [[ $factoring -lt 2 ]]; then
	echo "$1 is not composite nor prime"
else
	echo "$1 is prime!"
fi
end=`date +%s.%N`

runtime=$( echo "$end - $start" | bc -l )

echo "Runtime: $runtime seconds"
