#!/bin/bash -l
#SBATCH --job-name=hpc_mpi_poisson
#SBATCH --account=uzh8
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --output=output.log
#SBATCH --error=error.log

srun ./main
