#!/bin/bash

start=`date +%s.%N`

re='^[0-9]+$'

while test -n "$1"; do
	if ! [[ $1 =~ $re ]] ; then
	   echo "error: $1 Not an integer" >&2
	   shift
	   continue
	fi
	factoring=$(factor $1 | wc -w)

	if [[ $factoring -gt 2 ]]; then
		echo "$1 is composite!"
	elif [[ $factoring -lt 2 ]]; then
		echo "$1 is not composite nor prime"
	else
		echo "$1 is prime!"
	fi
	shift
done
end=`date +%s.%N`

runtime=$( echo "$end - $start" | bc -l )

echo "Runtime: $runtime seconds"
